"""Corrige ortografía (tildes y errores) en ADAPT-ECG_Marco_Teorico.docx
Usa límites de palabra (\b) para evitar sobre-correcciones en plurales/derivados.
"""
import re
from docx import Document

# Pares (incorrecto, correcto) — se aplican con \b para respetar límites de palabra
# Orden importa: formas más largas/específicas primero para evitar conflictos
CORRECCIONES = [
    # Errores verbales específicos (frases)
    ("capítulo continuo con", "capítulo continúa con"),
    ("se describo en", "se describió en"),
    ("llego a un consenso", "llegó a un consenso"),

    # Palabras sin tilde (se usa \b en la aplicación para evitar plurales/derivados)
    ("analisis", "análisis"),
    ("automaticos", "automáticos"),
    ("automaticas", "automáticas"),
    ("automatico", "automático"),
    ("automatica", "automática"),
    ("adquisicion", "adquisición"),
    ("actualizacion", "actualización"),
    ("agrupacion", "agrupación"),
    ("adopcion", "adopción"),
    ("alteracion", "alteración"),
    ("analogia", "analogía"),
    ("analogicos", "analógicos"),
    ("analogicas", "analógicas"),
    ("analogico", "analógico"),
    ("analogica", "analógica"),
    ("armonica", "armónica"),
    ("armonicos", "armónicos"),
    ("arboles", "árboles"),
    ("atipicas", "atípicas"),
    ("atipicos", "atípicos"),
    ("atipica", "atípica"),
    ("atipico", "atípico"),
    ("calibracion", "calibración"),
    ("capitulo", "capítulo"),
    ("CAPITULO", "CAPÍTULO"),
    ("cardiacas", "cardíacas"),
    ("cardiacos", "cardíacos"),
    ("cardiaca", "cardíaca"),
    ("cardiaco", "cardíaco"),
    ("categorias", "categorías"),
    ("caracteristicas", "características"),
    ("caracteristica", "característica"),
    ("clasificacion", "clasificación"),
    ("combinacion", "combinación"),
    ("comprension", "comprensión"),
    ("conexion", "conexión"),
    ("conduccion", "conducción"),
    ("convolucion", "convolución"),
    ("corazon", "corazón"),
    ("criticas", "críticas"),
    ("criticos", "críticos"),
    ("critica", "crítica"),
    ("critico", "crítico"),
    ("degradacion", "degradación"),
    ("deflexion", "deflexión"),
    ("diagnosticos", "diagnósticos"),
    ("diagnostico", "diagnóstico"),
    ("diseno", "diseño"),
    ("disenadas", "diseñadas"),
    ("disenados", "diseñados"),
    ("disenada", "diseñada"),
    ("disenado", "diseñado"),
    ("distorsion", "distorsión"),
    ("distribucion", "distribución"),
    ("economicos", "económicos"),
    ("economica", "económica"),
    ("ectopicos", "ectópicos"),
    ("ectopica", "ectópica"),
    ("ectopico", "ectópico"),
    ("electromiografico", "electromiográfico"),
    ("electromiografica", "electromiográfica"),
    ("enganoso", "engañoso"),
    ("epocas", "épocas"),
    ("episodicas", "episódicas"),
    ("episodicos", "episódicos"),
    ("estandares", "estándares"),
    ("Estandares", "Estándares"),
    ("estandar", "estándar"),
    ("Estandar", "Estándar"),
    ("estaticos", "estáticos"),
    ("estatica", "estática"),
    ("estatico", "estático"),
    ("evaluacion", "evaluación"),
    ("fenomeno", "fenómeno"),
    ("fenomenos", "fenómenos"),
    ("fibrilacion", "fibrilación"),
    ("generalizacion", "generalización"),
    ("grafico", "gráfico"),
    ("grafica", "gráfica"),
    ("graficos", "gráficos"),
    ("hemodinamico", "hemodinámico"),
    ("hemodinamica", "hemodinámica"),
    ("hiperparametros", "hiperparámetros"),
    ("hiperparametro", "hiperparámetro"),
    ("historicas", "históricas"),
    ("historicos", "históricos"),
    ("historica", "histórica"),
    ("historico", "histórico"),
    ("implicitas", "implícitas"),
    ("implicita", "implícita"),
    ("implicito", "implícito"),
    ("inclusion", "inclusión"),
    ("ingles", "inglés"),
    ("integracion", "integración"),
    ("interpretacion", "interpretación"),
    ("jerarquias", "jerarquías"),
    ("limitacion", "limitación"),
    ("limites", "límites"),
    ("limite", "límite"),
    ("maximos", "máximos"),
    ("maximas", "máximas"),
    ("maximo", "máximo"),
    ("maxima", "máxima"),
    ("maquinas", "máquinas"),
    ("metaforica", "metafórica"),
    ("metaforico", "metafórico"),
    ("metodos", "métodos"),
    ("metodo", "método"),
    ("Metricas", "Métricas"),
    ("metricas", "métricas"),
    ("metrica", "métrica"),
    ("miocardica", "miocárdica"),
    ("miocardico", "miocárdico"),
    ("minimas", "mínimas"),
    ("minimos", "mínimos"),
    ("minima", "mínima"),
    ("minimo", "mínimo"),
    ("multiples", "múltiples"),
    ("normalizacion", "normalización"),
    ("numeros", "números"),
    ("numero", "número"),
    ("numericas", "numéricas"),
    ("numericos", "numéricos"),
    ("numerica", "numérica"),
    ("numerico", "numérico"),
    ("obstaculo", "obstáculo"),
    ("obstaculos", "obstáculos"),
    ("Organizacion", "Organización"),
    ("organizacion", "organización"),
    ("parametros", "parámetros"),
    ("parametro", "parámetro"),
    ("parametrica", "paramétrica"),
    ("parametrico", "paramétrico"),
    ("paroxisticas", "paroxísticas"),
    ("perdidas", "pérdidas"),
    ("perdida", "pérdida"),
    ("plasticos", "plásticos"),
    ("plastica", "plástica"),
    ("plastico", "plástico"),
    ("podrian", "podrían"),
    ("politicas", "políticas"),
    ("politica", "política"),
    ("posicion", "posición"),
    ("practicos", "prácticos"),
    ("practicas", "prácticas"),
    ("practico", "práctico"),
    ("practica", "práctica"),
    ("precision", "precisión"),
    ("pronosticos", "pronósticos"),
    ("pronostico", "pronóstico"),
    ("programatica", "programática"),
    ("proporcion", "proporción"),
    ("propositos", "propósitos"),
    ("proposito", "propósito"),
    ("publicas", "públicas"),
    ("publicos", "públicos"),
    ("publica", "pública"),
    ("publico", "público"),
    ("retencion", "retención"),
    ("regularizacion", "regularización"),
    ("repolarizacion", "repolarización"),
    ("representacion", "representación"),
    ("retropropagacion", "retropropagación"),
    ("seccion", "sección"),
    ("segmentacion", "segmentación"),
    ("Segun", "Según"),
    ("segun", "según"),
    ("simultanea", "simultánea"),
    ("subita", "súbita"),
    ("tambien", "también"),
    ("tamano", "tamaño"),
    ("tamanos", "tamaños"),
    ("Tecnica", "Técnica"),
    ("tecnicas", "técnicas"),
    ("tecnicos", "técnicos"),
    ("tecnica", "técnica"),
    ("tecnico", "técnico"),
    ("tension", "tensión"),
    ("terminos", "términos"),
    ("termino", "término"),
    ("traslacion", "traslación"),
    ("ultimas", "últimas"),
    ("ultimos", "últimos"),
    ("utiles", "útiles"),
    ("util", "útil"),
    ("ventriculos", "ventrículos"),
    ("ventriculo", "ventrículo"),
    ("Estadistica", "Estadística"),
    ("estadisticas", "estadísticas"),
    ("estadistica", "estadística"),
    ("electrocardiograficas", "electrocardiográficas"),
    ("electrocardiografica", "electrocardiográfica"),
    ("electrocardiografico", "electrocardiográfico"),
    ("ademas", "además"),
    ("activacion", "activación"),
    ("anotacion", "anotación"),
    ("aplicacion", "aplicación"),
    ("aproximacion", "aproximación"),
    ("areas", "áreas"),
    ("area", "área"),
    ("colocacion", "colocación"),
    ("comparacion", "comparación"),
    ("comparticion", "compartición"),
    ("comun", "común"),
    ("conservacion", "conservación"),
    ("contraccion", "contracción"),
    ("contribucion", "contribución"),
    ("conversion", "conversión"),
    ("derivacion", "derivación"),
    ("despolarizacion", "despolarización"),
    ("desviacion", "desviación"),
    ("deteccion", "detección"),
    ("direccion", "dirección"),
    ("duracion", "duración"),
    ("eleccion", "elección"),
    ("extraccion", "extracción"),
    ("fusion", "fusión"),
    ("identificacion", "identificación"),
    ("investigacion", "investigación"),
    ("mision", "misión"),
    ("operacion", "operación"),
    ("optimizacion", "optimización"),
    ("penalizacion", "penalización"),
    ("ponderacion", "ponderación"),
    ("decision", "decisión"),
    ("produccion", "producción"),
    ("propagacion", "propagación"),
    ("relajacion", "relajación"),
    ("resolucion", "resolución"),
    ("respiracion", "respiración"),
    ("seleccion", "selección"),
    ("union", "unión"),
    ("variacion", "variación"),
    ("anaden", "añaden"),
    ("atencion", "atención"),
    ("adaptacion", "adaptación"),
    ("biofisicos", "biofísicos"),
    ("cientificas", "científicas"),
    ("cientificos", "científicos"),
    ("cientifica", "científica"),
    ("cientifico", "científico"),
    ("informacion", "información"),
    ("medicos", "médicos"),
    ("medica", "médica"),
    ("medicas", "médicas"),
    ("medico", "médico"),
    ("monitorizacion", "monitorización"),
    ("opcion", "opción"),
    ("opciones", "opciones"),  # ya correcto sin acento en plural
    ("pequeno", "pequeño"),
    ("pequenos", "pequeños"),
    ("pequena", "pequeña"),
    ("pequenas", "pequeñas"),
    ("relacion", "relación"),
    ("relaciones", "relaciones"),  # ya correcto sin acento en plural
    ("nucleo", "núcleo"),
    ("nucleos", "núcleos"),
    ("teorico", "teórico"),
    ("teorica", "teórica"),
    ("teoricos", "teóricos"),
    ("teoricas", "teóricas"),
    ("TEORICO", "TEÓRICO"),
    ("biofisicas", "biofísicas"),
    ("biofisica", "biofísica"),
    ("biofisico", "biofísico"),
    ("computo", "cómputo"),
    ("desafio", "desafío"),
    ("desafios", "desafíos"),
    ("electricas", "eléctricas"),
    ("electrica", "eléctrica"),
    ("electrico", "eléctrico"),
    ("electricos", "eléctricos"),
    ("funcion", "función"),
    ("repeticion", "repetición"),
    ("repeticiones", "repeticiones"),  # ya correcto sin acento en plural
    ("senales", "señales"),
    ("senal", "señal"),
    ("farmacologicos", "farmacológicos"),
    ("farmacologica", "farmacológica"),
    ("farmacologico", "farmacológico"),
    ("morfologicas", "morfológicas"),
    ("morfologicos", "morfológicos"),
    ("morfologica", "morfológica"),
    ("morfologico", "morfológico"),
    ("morfologia", "morfología"),
    ("fisiologicos", "fisiológicos"),
    ("fisiologicas", "fisiológicas"),
    ("fisiologico", "fisiológico"),
    ("fisiologica", "fisiológica"),
    ("biologicas", "biológicas"),
    ("biologicos", "biológicos"),
    ("biologica", "biológica"),
    ("biologico", "biológico"),
    ("patologicas", "patológicas"),
    ("patologicos", "patológicos"),
    ("patologica", "patológica"),
    ("patologico", "patológico"),
    ("Patologias", "Patologías"),
    ("patologias", "patologías"),
    ("tecnologias", "tecnologías"),
    ("biomedicas", "biomédicas"),
    ("biomedicos", "biomédicos"),
    ("biomedica", "biomédica"),
    ("biomedico", "biomédico"),
    ("metodologia", "metodología"),
    ("tipicamente", "típicamente"),
    ("tipicas", "típicas"),
    ("tipicos", "típicos"),
    ("tipica", "típica"),
    ("tipico", "típico"),
    ("clinicamente", "clínicamente"),
    ("clinicas", "clínicas"),
    ("clinicos", "clínicos"),
    ("clinica", "clínica"),
    ("clinico", "clínico"),
    ("especificamente", "específicamente"),
    ("especificas", "específicas"),
    ("especificos", "específicos"),
    ("especifica", "específica"),
    ("especifico", "específico"),
    ("drasticamente", "drásticamente"),
    ("rapidamente", "rápidamente"),
    ("facilmente", "fácilmente"),
    ("estadisticamente", "estadísticamente"),
    ("historicamente", "históricamente"),
    ("electromiograficos", "electromiográficos"),
]

# Frases multi-palabra (NO usan \b, son reemplazos literales de frases)
FRASES = [
    ("capítulo continuo con", "capítulo continúa con"),
    ("se describo en", "se describió en"),
    ("llego a un consenso", "llegó a un consenso"),
    ("isquemia miocardica", "isquemia miocárdica"),
    ("MARCO TEORICO", "MARCO TEÓRICO"),
    # "está" como verbo (solo donde es verbo, no demostrativo)
    ("capitulo continua con", "capítulo continúa con"),
    ("registro esta almacenado", "registro está almacenado"),
    ("biomédicas esta compuesta", "biomédicas está compuesta"),
    ("ECG_CNN) esta compuesta", "ECG_CNN) está compuesta"),
    ("buffer esta lleno", "buffer está lleno"),
]


def corregir_texto(texto):
    # Primero frases multi-palabra (literales)
    for inc, cor in FRASES:
        texto = texto.replace(inc, cor)

    # Luego palabras individuales con límite de palabra
    for inc, cor in CORRECCIONES:
        texto = re.sub(r'\b' + re.escape(inc) + r'\b', cor, texto)

    # "mas" como adverbio (límite de palabra)
    texto = re.sub(r'\bmas\b', 'más', texto)
    # "ano" como sustantivo "año"
    texto = re.sub(r'\bano\b', 'año', texto)

    return texto


def procesar_docx(ruta_entrada, ruta_salida):
    doc = Document(ruta_entrada)
    cambios = 0

    for para in doc.paragraphs:
        for run in para.runs:
            original = run.text
            corregido = corregir_texto(original)
            if corregido != original:
                run.text = corregido
                cambios += 1

    for tabla in doc.tables:
        for fila in tabla.rows:
            for celda in fila.cells:
                for para in celda.paragraphs:
                    for run in para.runs:
                        original = run.text
                        corregido = corregir_texto(original)
                        if corregido != original:
                            run.text = corregido
                            cambios += 1

    doc.save(ruta_salida)
    print(f"Correcciones aplicadas en {cambios} runs. Guardado en: {ruta_salida}")


if __name__ == "__main__":
    procesar_docx("docs/ADAPT-ECG_Marco_Teorico.docx", "docs/ADAPT-ECG_Marco_Teorico.docx")
